#!/usr/bin/env ruby

$previous_line_was_code = false

class String
  def fix_headers
    self.gsub(/^(#+)/) do |sub|
      "h#{sub.size}."
    end
  end

  def fix_code
    ret = self.gsub(/^\s\s\s\s/) do |sub|
      if $previous_line_was_code
      else
        "bc. "
      end
    end
    if self.scan(/^\s\s\s\s/).empty?
      $previous_line_was_code = false
    else
      $previous_line_was_code = true
    end
    ret
  end

  def fix_inline_code
    self.gsub("`", "@")
  end
end

in_file = ARGV[0]
out_file = in_file.gsub(".md", ".txtl")

out = File.open(out_file, "w")

File.open(in_file, "r") do |f|
  f.readlines.each do |line|
    line = line.fix_headers.fix_code.fix_inline_code
    out << line
  end
end


out.close
