#!/usr/bin/env bash

RED="\[\033[0;31m\]"
GREEN="\[\033[0;32m\]"
YELLOW="\[\033[0;33m\]"
WHITE="\[\033[0;37m\]"

function find_svn_root {
	current_pwd="./"
	is_svn_dir=$(ls -al $current_pwd | ack \.svn | wc -l)
	while [ $is_svn_dir -eq 1 ]; do
		current_pwd="${current_pwd}../"
		is_svn_dir=$(ls -a $current_pwd | ack \.svn | wc -l)
	done
	echo "$(echo -e ${current_pwd} | sed 's/...$//')"
}

function parse_vc_branch {
	parse_git_branch || parse_svn_branch
}

function parse_git_branch {
  ref=$(git symbolic-ref HEAD 2> /dev/null) || return
  echo " ("${ref#refs/heads/}$(num_git_commits_ahead)")"
}

function parse_svn_branch {
	root=$(find_svn_root)
	depth=`ruby -e "puts '${root}'.split('/').size - 1"`
	ref=$(svn info 2> /dev/null) || return
	num_changed=$(svn st $root | wc -l)
	num_con=$(svn st $root | ack ^C | wc -l) 
	num_mod=$(svn st $root | ack ^M | wc -l)
	num_add=$(svn st $root | ack ^A | wc -l)
	num_del=$(svn st $root | ack ^D | wc -l)
	num_new=$(svn st $root | ack "^\?" | wc -l)
	printf " depth:$depth "
	if [ $num_changed -eq 0 ]; then
		echo "(clean)"
	else
		if [ $num_con -gt 0 ]; then
			printf "\e[31m( $((num_con)) conflicted files)"
		else
			printf "\e[37m( \e[32m$((num_add)) \e[31m$((num_del)) \e[33m$((num_mod)) \e[36m$((num_new)) \e[37m)"
		fi
	fi
}

function num_git_commits_ahead {
    num=$(git status 2> /dev/null | grep "Your branch is ahead of" | awk '{split($0,a," "); print a[9];}' 2> /dev/null) || return
    if [[ "$num" != "" ]]; then
  echo "+$num"
    fi
}

PS1="$GREEN\w$YELLOW\$(parse_vc_branch) $GREEN\$ $WHITE"